### ISSUE TITLE
Screen Reader Accessibility on Windows

### ISSUE THREAD

**Issue by Gamulation** [kaylh/old-RetroBat-obsolete#109]
Hi.
I am fully blind and would like to use this program. However, the tool I'm using to navigate and get speech does not work with the program.
Can this be looked into? I have a suggestion. Don't know if it's possible, but try getting this in: https://github.com/nvaccess/nvda/tree/master/extras/controllerClient
This lets my screen reader get information from the program so it can speak the info to me. I have no idea how to program, but if it's possible to ad it it would be really awesome!

**Comment by kaylh** [comment]
Hello, sorry for this very late answer. The dev team is more active on discord or the forum. You will have better chance to ask for a feature directly on the RetroBat discord. However, you can activate speech on screen with F5 on the keyboard.
