### ISSUE TITLE
[Feature Request] Option to change description scrollspeed

### ISSUE THREAD

**Issue by user18081972** [kaylh/old-RetroBat-obsolete#121]
I am a pretty slow reader, and I am unable to read the descriptions of games before they scroll out of frame.

I tried looking for a way to change the scroll speed, but all I could find was more people with the same problem:
reddit.com/r/RetroPie/comments/8n5hh3/is_it_possible_to_slow_the_scrolling_speed_for/

could someone add a setting to RetroBat that allows me to set the scroll speed of the game descriptions slower?

Thanks!

**Comment by kaylh** [comment]
Hello, sorry for this very late answer. The dev team is more active on discord or the forum. You will have better chance to ask for this feature directly on the RetroBat discord where the EmulationStation developper will read your request. I'm personally not in charge of the interface
