### ISSUE TITLE
Hide es when running a game option for windows games only

### ISSUE THREAD

**Issue by Dovey79** [kaylh/old-RetroBat-obsolete#133]
Hello.

Great work on 5.3. Much appreciated.

As of now I have emulationstation hidden when running a game. It is the menu option in system settings, front end developer options, hide emulationstation when running a game.
However some windows games do not run with this option enabled. They run fine in retrobat with it disabled.

Could this be added to advanced system options for windows games so I can turn it off for games that require it without having to change the global option?

Thanks for your hard work.

**Comment by Dovey79** [comment]
Sorry its disabled and some windows games need it enabled :)

But the request remains the same. Thanks

**Comment by kaylh** [comment]
Hello,
Sorry for the very late answer. The dev team is more active on discord or the forum, especially when it concerns features request.
This feature concerns EmulationStation directly, you will have better chance to ask to ES dev on discord. I'm not in charge of ES.
Did you read the FAQ or the Wiki, you will find usefull informations to run games with client such as steam or epic launcher.
