### ISSUE TITLE
Autodetect openbor version for game Bare Knuckles III Yesterday Once More

### ISSUE THREAD

**Issue by samuk190** [kaylh/old-RetroBat-obsolete#134]
It should load openbor build 3591 but instead it runs on latest and crashes.

**Comment by Tartifless** [comment]
Hello,
There is currently no mechanism to use multiple openbor versions.

**Comment by samuk190** [comment]
> Hello, There is currently no mechanism to use multiple openbor versions.

anyway I can contribute to help develop that mechanism ?

**Comment by kaylh** [comment]
Hello,
> anyway I can contribute to help develop that mechanism ?

Maybe you can make a suggestion ?

But until now we don't put multiple versions of openbor because in that case we'll have almost one version for one game and an endless work for controllers autoconfiguration.

**Comment by samuk190** [comment]
suggestion: make a folder where you can place all build versions of specific emulator, and when choosing which emulator it will run on specific game it will list the builds you've put in the folder first. What do you think ?  also as far as I know the controller  autoconfiguration for openbor (LATEST) would work on any other version of openBor
