### ISSUE TITLE
v5.0 Sega Dreamcast default button mapping incorrect

### ISSUE THREAD

**Issue by sammy2142** [kaylh/old-RetroBat-obsolete#95]
For some reason the default button mapping is messed up for all Dreamcast cores. The R button doesn't seem to be mapped on a xbox one controller.

Edit: tried changing control driver from sdl to xinput with no effect. For some reason this system doesn't want to work with my right analogue trigger

Edit: works fine in standalone retroarch

**Comment by Tartifless** [comment]
Hi, how is your controller set in es_input.cfg ?

**Comment by Tartifless** [comment]
Also, libretro documentation for flycast states:
"When using an Xbox 360 Controller, analog triggers don't work properly. Use the bumpers instead."

**Comment by sammy2142** [comment]
Hi I was using a xbox one controller.
It works fine in standalone retroarch (1.13.0) and flycast (b232a10) by default.

I'm not sure why it doesn't work in retrobat

Unfortunately I switched back to standalone retroarch over Christmas and no longer have my es_input.cfg file :(

**Comment by kaylh** [comment]
Hello, did you tried with newer versions of RetroBat ?
